apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::339712846046:user/admin
      username: admin
      groups:
        - system:masters
    - userarn: arn:aws:iam::339712846046:user/sealstorage-user
      username: readonly
      groups:
        - system:masters
