apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-script
        image: busybox
        command:
          - /bin/sh
          - -c
          - |
            cp /config/startup-script.sh /scripts/startup-script.sh
            chmod +x /scripts/startup-script.sh
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: scripts
          mountPath: /scripts
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: scripts
          mountPath: /scripts
        command: ["/bin/sh"]
        args:
          - -c
          - |
            /scripts/startup-script.sh
      volumes:
      - name: html
        emptyDir: {}
      - name: config-volume
        configMap:
          name: html-config
      - name: scripts
        emptyDir: {}
