apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
data:
  startup-script.sh: |
    #!/bin/sh
    set -x  # Enable debug mode
    cat <<EOF > /usr/share/nginx/html/index.html
    <!DOCTYPE html>
    <html>
    <head>
      <title>NGINX Pod Information</title>
    </head>
    <body>
      <h1>NGINX Pod Information</h1>
      <p><b>Pod Name:</b> ${POD_NAME}</p>
      <p><b>Node Name:</b> ${NODE_NAME}</p>
      <p><b>Namespace:</b> ${POD_NAMESPACE}</p>
      <p><b>Pod IP:</b> ${POD_IP}</p>
    </body>
    </html>
    EOF
    nginx -g 'daemon off;'
