name: Terraform Plan

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.7 # Match with Local Terraform version

    - name: 'Terraform Init and Plan'
      working-directory: ./infrastructure
      run: terraform init && terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
        AWS_PROFILE: 'SealStorage'
